---
title: "Proves_PropagationKernel"
format: html
editor: visual
---

## Grafs

Funció que retorna la matriu de propagació.


```{r}
library(Matrix) 

matriu_propagacio <- function(G){
  

  T <- as_adjacency_matrix(G, sparse = TRUE)
  

  suma_files <- Matrix::rowSums(T)
  d <- ifelse(suma_files == 0, 1, 0)
  d
  suma_files[suma_files == 0] <- 1
  suma_files
  D_inv <- Matrix::Diagonal(x = 1/suma_files)
  D_d   <- Matrix::Diagonal(x = d)
  
  T_prop <- (D_inv %*% T) + D_d
  

  return(t(T_prop))
}
```

Funció que retorna els vectors $p_i$. És una funció auxiliar no l'utilitz.

```{r}
library(igraph)

vector_p <- function(etiquetes_graf, pesos, conjunt_etiquetes){
  
  p <- numeric(length(conjunt_etiquetes))
  idx <- match(etiquetes_graf, conjunt_etiquetes)
  p[idx] <- pesos
  return(p)

}
```

Funció per fer proves de manera aleatòria. És molt probable que hi hagui etiquetes repetides, ens interessa.

```{r}
library(igraph)

generar_graf_aleatori <- function(n_min,n_max,a_min,a_max){
  
num_nodes <- sample(n_min:n_max, 1)
num_arestes <- min(sample(a_min:a_max, 1), num_nodes*(num_nodes - 1))

g <- sample_gnm(n = num_nodes,
                    m = num_arestes,
                    directed = TRUE,
                    loops = FALSE)


V(g)$abundance <- sample(1:1000, num_nodes, replace = TRUE)
V(g)$name <- paste0("node_", 1:num_nodes)
return(g)
}
```

```{r, echo=FALSE}
library(igraph)

maj_comp_con <- function(g, mode = "weak") {
  comp <- components(g, mode = mode)
  idx  <- which.max(comp$csize)
  comp_final <- induced_subgraph(g, which(comp$membership == idx))
  return(comp_final)
}

```

```{r, echo=FALSE}
library(Matrix)
library(lsa)

Prop_att_ker <- function(G1, G2,iteracions){
  G1 <- maj_comp_con(G1)
  G2 <- maj_comp_con(G2)
  
  if (iteracions == FALSE){
    a <- diameter(G1, directed = TRUE, unconnected = TRUE)
    b <- diameter(G2, directed = TRUE, unconnected = TRUE)
    iteracions <- max(a,b)
  }
   
  
  etiquetes_1 <- V(G1)$name
  etiquetes_2 <- V(G2)$name
  conjunt_etiquetes <- unique(c(etiquetes_1,etiquetes_2))
  
  pesos_1 <- as.numeric(V(G1)$abundance)
  pesos_2 <- as.numeric(V(G2)$abundance)
  
  idx1 <- match(etiquetes_1, conjunt_etiquetes)
  idx2 <- match(etiquetes_2, conjunt_etiquetes)
  
  p1 <- numeric(length(conjunt_etiquetes))
  p2 <- numeric(length(conjunt_etiquetes))
  p1[idx1] <- pesos_1
  p2[idx2] <- pesos_2
  
  MP1 <- matriu_propagacio(G1)
  MP2 <- matriu_propagacio(G2)
  
  sim = cosine(p1,p2)
  
  if (iteracions > 1){
    for (i in 2:iteracions){
    pesos_1 <- MP1 %*% pesos_1
    pesos_2 <- MP2 %*% pesos_2
    
    p1[idx1] <- pesos_1
    p2[idx2] <- pesos_2
    
    sim <- sim + cosine(p1,p2)
    } 
  }
  
return(sim)
}
  
```

```{r, echo=FALSE}
library(igraph)
library(tidyverse)


adj_1 <- matrix(c(0,1,0,1,0,0,0,0, 0,0,1,0,0,0,0,0, 0,0,0,0,0,1,0,0, 0,0,0,0,0,0,0,0, 0,0,0,1,0,1,0,0, 0,0,0,0,0,0,0,0, 0,0,0,0,0,0,0,1, 0,0,0,0,0,0,1,0), nrow = 8, ncol = 8, byrow = TRUE)
g1 <- graph_from_adjacency_matrix(
  adj_1, mode = c("directed")
  ) %>% 
    set_vertex_attr("abundance", value = c(10,16,8,6,10,12,10,10)) %>% 
    set_vertex_attr("name", value = c("A","B","C","D","E","F","p","q"))

adj_2 <- matrix(c(0,1,0,1,0,0, 0,0,1,0,0,0, 0,0,0,0,0,1, 0,0,0,0,0,0, 0,0,0,1,0,1, 0,0,0,0,0,0), nrow = 6, ncol = 6, byrow = TRUE)
g2 <- graph_from_adjacency_matrix(
  adj_2, mode = c("directed")
  ) %>% 
    set_vertex_attr("abundance", value = c(5,8,4,3,5,6)) %>% 
    set_vertex_attr("name", value = c("A","B","C","D","E","F"))

adj_3 <- matrix(c(0,0,0,0,0,0, 1,0,0,0,0,0, 0,1,0,0,0,0, 1,0,0,0,1,0, 0,0,0,0,0,0, 0,0,1,0,1,0), nrow = 6, ncol = 6, byrow = TRUE)
g3 <- graph_from_adjacency_matrix(
  adj_3, mode = c("directed")
  ) %>% 
    set_vertex_attr("abundance", value = c(10,16,8,6,10,12))%>% 
    set_vertex_attr("name", value = c("A","B","C","D","E","F"))

adj_4 <- matrix(c(0,1,0,1,0,0, 0,0,1,0,0,0, 0,0,0,0,0,0, 0,0,0,0,0,0, 0,0,0,1,0,1, 0,0,0,0,0,0), nrow = 6, ncol = 6, byrow = TRUE)
g4 <- graph_from_adjacency_matrix(
  adj_4, mode = c("directed")
  ) %>% 
    set_vertex_attr("abundance", value = c(7,2,11,5,13,3)) %>% 
    set_vertex_attr("name", value = c("A","B","C","D","E","F"))

adj_5 <- matrix(c(0,1,1,0,0,0, 0,0,0,0,0,1, 0,0,0,0,1,1, 0,0,1,0,0,0, 0,0,0,1,0,0, 1,0,0,0,1,0), nrow = 6, ncol = 6, byrow = TRUE)
g5 <- graph_from_adjacency_matrix(
  adj_5, mode = c("directed")
  ) %>% 
    set_vertex_attr("abundance", value = c(1:6)) %>% 
    set_vertex_attr("name", value = c("A","B","C","D","E","F"))

adj_6 <- matrix(c(0,1,0,0,0,1, 0,0,1,0,0,1, 0,0,0,0,1,1, 0,0,1,0,0,0, 0,0,0,1,0,0, 1,0,0,0,1,0), nrow = 6, ncol = 6, byrow = TRUE)
g6 <- graph_from_adjacency_matrix(
  adj_6, mode = c("directed")
  ) %>% 
    set_vertex_attr("abundance", value = c(12,18,26,26,32,9)) %>% 
    set_vertex_attr("name", value = c("A","B","C","D","E","F"))

llista <- list(g1,g2,g3,g4,g5,g6)  
M <- matrix(0, 6, 6)
  
  for (i in 1:6) {
    for (j in 1:6) {
      M[i, j] <- Prop_att_ker(llista[[i]], llista[[j]], iteracions = FALSE)
    }
  }
```

```{r, echo=FALSE}
library(igraph)


g1 <- generar_graf_aleatori(100,101,20000,20500)
g2 <- generar_graf_aleatori(100,101,4000,4200)

a <- Prop_att_ker(g1,g2, iteracions = 3)

```

```{r, echo=FALSE}
library(igraph)


llista_grafs <- graphs

n <- length(llista_grafs) 
M <- matrix(0, n, n)       

for (i in 1:n) {
  for (j in i:n) {
    val <- Prop_att_ker(llista_grafs[[i]], llista_grafs[[j]], iteracions = FALSE)
    
    M[i,j] <- val
    M[j,i] <- val
  }
}

arrels_diag <- sqrt(diag(M))

denominadors <- outer(arrels_diag, arrels_diag, FUN = "*")

M_sim <- M / denominadors

```



